import type { VerticalManifestInput } from "../../manifest";

type Medication = VerticalManifestInput["safety"]["medicationCatalog"][number];

/**
 * Catálogo de referencia para verificar nombre, unidad y dosis máxima por
 * toma en adultos. No es un vademécum: sirve para marcar lo que conviene
 * revisar. La dosis nunca se completa automáticamente.
 */
export const MEDICATION_CATALOG: Medication[] = [
  { name: "paracetamol", aliases: ["acetaminofen"], classes: ["analgesicos"], units: ["mg", "g", "gotas", "comprimidos"], maxSingleDose: 1000 },
  { name: "ibuprofeno", classes: ["aines"], units: ["mg", "comprimidos"], maxSingleDose: 800 },
  { name: "diclofenac", aliases: ["diclofenaco"], classes: ["aines"], units: ["mg", "comprimidos"], maxSingleDose: 75 },
  { name: "aspirina", aliases: ["acido acetilsalicilico", "aas"], classes: ["aines", "salicilatos"], units: ["mg", "comprimidos"], maxSingleDose: 1000 },
  { name: "ketorolac", aliases: ["ketorolaco"], classes: ["aines"], units: ["mg", "comprimidos"], maxSingleDose: 60 },
  { name: "dipirona", aliases: ["metamizol"], classes: ["analgesicos", "pirazolonas"], units: ["mg", "g", "gotas", "comprimidos"], maxSingleDose: 2000 },
  { name: "tramadol", classes: ["opioides"], units: ["mg", "gotas", "comprimidos"], maxSingleDose: 100 },
  { name: "amoxicilina", aliases: ["amoxicilina clavulanico"], classes: ["penicilinas", "betalactamicos"], units: ["mg", "g", "comprimidos", "ml"], maxSingleDose: 1000 },
  { name: "cefalexina", classes: ["cefalosporinas", "betalactamicos"], units: ["mg", "g", "comprimidos", "ml"], maxSingleDose: 1000 },
  { name: "azitromicina", classes: ["macrolidos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 500 },
  { name: "ciprofloxacina", classes: ["quinolonas"], units: ["mg", "comprimidos"], maxSingleDose: 750 },
  { name: "nitrofurantoina", classes: ["antibioticos"], units: ["mg", "comprimidos"], maxSingleDose: 100 },
  { name: "enalapril", classes: ["ieca"], units: ["mg", "comprimidos"], maxSingleDose: 40 },
  { name: "losartan", classes: ["ara2"], units: ["mg", "comprimidos"], maxSingleDose: 100 },
  { name: "amlodipina", classes: ["bloqueantes calcicos"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "hidroclorotiazida", classes: ["diureticos"], units: ["mg", "comprimidos"], maxSingleDose: 50 },
  { name: "atenolol", classes: ["betabloqueantes"], units: ["mg", "comprimidos"], maxSingleDose: 100 },
  { name: "metformina", classes: ["biguanidas"], units: ["mg", "g", "comprimidos"], maxSingleDose: 1000 },
  { name: "insulina", aliases: ["insulina nph", "insulina glargina"], classes: ["insulinas"], units: ["ui"] },
  { name: "atorvastatina", classes: ["estatinas"], units: ["mg", "comprimidos"], maxSingleDose: 80 },
  { name: "omeprazol", classes: ["ibp"], units: ["mg", "comprimidos"], maxSingleDose: 40 },
  { name: "levotiroxina", classes: ["hormonas tiroideas"], units: ["mcg", "comprimidos"], maxSingleDose: 300 },
  { name: "salbutamol", classes: ["broncodilatadores"], units: ["puff", "mg", "gotas"] },
  { name: "prednisona", aliases: ["meprednisona"], classes: ["corticoides"], units: ["mg", "comprimidos"], maxSingleDose: 80 },
  { name: "clonazepam", classes: ["benzodiacepinas"], units: ["mg", "gotas", "comprimidos"], maxSingleDose: 2 },
  { name: "alprazolam", classes: ["benzodiacepinas"], units: ["mg", "comprimidos"], maxSingleDose: 2 },
  { name: "sertralina", classes: ["isrs"], units: ["mg", "comprimidos"], maxSingleDose: 200 },
  { name: "enoxaparina", classes: ["anticoagulantes"], units: ["mg", "ui"], maxSingleDose: 150 },
  { name: "naproxeno", classes: ["aines"], units: ["mg", "comprimidos"], maxSingleDose: 550 },
  { name: "meloxicam", classes: ["aines"], units: ["mg", "comprimidos"], maxSingleDose: 15 },
  { name: "ketoprofeno", classes: ["aines"], units: ["mg", "comprimidos"], maxSingleDose: 100 },
  { name: "celecoxib", classes: ["aines", "coxibs"], units: ["mg", "comprimidos"], maxSingleDose: 400 },
  { name: "morfina", classes: ["opioides"], units: ["mg", "ml"], maxSingleDose: 30 },
  { name: "codeina", classes: ["opioides"], units: ["mg", "gotas", "comprimidos"], maxSingleDose: 60 },
  { name: "pregabalina", classes: ["gabapentinoides"], units: ["mg", "comprimidos"], maxSingleDose: 300 },
  { name: "gabapentina", classes: ["gabapentinoides"], units: ["mg", "comprimidos"], maxSingleDose: 1200 },
  { name: "colchicina", classes: ["antigotosos"], units: ["mg", "comprimidos"], maxSingleDose: 1.2 },
  { name: "alopurinol", classes: ["antigotosos"], units: ["mg", "comprimidos"], maxSingleDose: 300 },
  { name: "cefuroxima", classes: ["cefalosporinas", "betalactamicos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 500 },
  { name: "ceftriaxona", classes: ["cefalosporinas", "betalactamicos"], units: ["mg", "g"], maxSingleDose: 2000 },
  { name: "claritromicina", classes: ["macrolidos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 500 },
  { name: "doxiciclina", classes: ["tetraciclinas"], units: ["mg", "comprimidos"], maxSingleDose: 200 },
  { name: "levofloxacina", classes: ["quinolonas"], units: ["mg", "comprimidos"], maxSingleDose: 750 },
  { name: "trimetoprima sulfametoxazol", aliases: ["tmp sms", "cotrimoxazol", "bactrim"], classes: ["sulfonamidas"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 960 },
  { name: "metronidazol", classes: ["nitroimidazoles"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 500 },
  { name: "fluconazol", classes: ["azoles"], units: ["mg", "comprimidos"], maxSingleDose: 400 },
  { name: "aciclovir", classes: ["antivirales"], units: ["mg", "comprimidos"], maxSingleDose: 800 },
  { name: "valaciclovir", classes: ["antivirales"], units: ["mg", "g", "comprimidos"], maxSingleDose: 2000 },
  { name: "bisoprolol", classes: ["betabloqueantes"], units: ["mg", "comprimidos"], maxSingleDose: 20 },
  { name: "carvedilol", classes: ["betabloqueantes"], units: ["mg", "comprimidos"], maxSingleDose: 50 },
  { name: "propranolol", classes: ["betabloqueantes"], units: ["mg", "comprimidos"], maxSingleDose: 80 },
  { name: "captopril", classes: ["ieca"], units: ["mg", "comprimidos"], maxSingleDose: 50 },
  { name: "valsartan", classes: ["ara2"], units: ["mg", "comprimidos"], maxSingleDose: 320 },
  { name: "furosemida", classes: ["diureticos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 80 },
  { name: "espironolactona", classes: ["diureticos"], units: ["mg", "comprimidos"], maxSingleDose: 100 },
  { name: "clopidogrel", classes: ["antiagregantes"], units: ["mg", "comprimidos"], maxSingleDose: 600 },
  { name: "apixaban", classes: ["anticoagulantes"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "rivaroxaban", classes: ["anticoagulantes"], units: ["mg", "comprimidos"], maxSingleDose: 20 },
  { name: "acenocumarol", classes: ["anticoagulantes", "cumarinicos"], units: ["mg", "comprimidos"], maxSingleDose: 8 },
  { name: "digoxina", classes: ["digitalicos"], units: ["mg", "comprimidos"], maxSingleDose: 0.5 },
  { name: "amiodarona", classes: ["antiarritmicos"], units: ["mg", "comprimidos"], maxSingleDose: 400 },
  { name: "glibenclamida", classes: ["sulfonilureas"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "sitagliptina", classes: ["idpp4"], units: ["mg", "comprimidos"], maxSingleDose: 100 },
  { name: "pantoprazol", classes: ["ibp"], units: ["mg", "comprimidos"], maxSingleDose: 40 },
  { name: "metoclopramida", classes: ["antiemeticos"], units: ["mg", "gotas", "comprimidos"], maxSingleDose: 10 },
  { name: "ondansetron", classes: ["antiemeticos"], units: ["mg", "comprimidos"], maxSingleDose: 8 },
  { name: "dexametasona", classes: ["corticoides"], units: ["mg", "ml"], maxSingleDose: 16 },
  { name: "betametasona", classes: ["corticoides"], units: ["mg", "ml", "gotas"], maxSingleDose: 12 },
  { name: "budesonida", classes: ["corticoides"], units: ["mcg", "mg", "puff"], maxSingleDose: 800 },
  { name: "montelukast", classes: ["antileucotrienos"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "cetirizina", classes: ["antihistaminicos"], units: ["mg", "gotas", "comprimidos"], maxSingleDose: 10 },
  { name: "desloratadina", classes: ["antihistaminicos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 5 },
  { name: "fluoxetina", classes: ["isrs"], units: ["mg", "comprimidos"], maxSingleDose: 80 },
  { name: "escitalopram", classes: ["isrs"], units: ["mg", "comprimidos", "gotas"], maxSingleDose: 20 },
  { name: "quetiapina", classes: ["antipsicoticos"], units: ["mg", "comprimidos"], maxSingleDose: 400 },
  { name: "risperidona", classes: ["antipsicoticos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 6 },
  { name: "lorazepam", classes: ["benzodiacepinas"], units: ["mg", "comprimidos"], maxSingleDose: 4 },
  { name: "diazepam", classes: ["benzodiacepinas"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "zolpidem", classes: ["hipnoticos"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "sulfato ferroso", aliases: ["hierro"], classes: ["antianemicos"], units: ["mg", "gotas", "comprimidos"], maxSingleDose: 200 },
  { name: "vitamina d", aliases: ["colecalciferol"], classes: ["vitaminas"], units: ["ui", "gotas", "comprimidos"] },
  { name: "adrenalina", aliases: ["epinefrina"], classes: ["simpaticomimeticos"], units: ["mg", "ml"], maxSingleDose: 1 },
  { name: "tiotropio", classes: ["broncodilatadores"], units: ["mcg", "puff"], maxSingleDose: 18 },
  { name: "ipratropio", classes: ["broncodilatadores"], units: ["mcg", "puff", "gotas"] },
  { name: "tamsulosina", classes: ["alfabloqueantes"], units: ["mg", "comprimidos"], maxSingleDose: 0.8 },
  { name: "finasteride", aliases: ["finasterida"], classes: ["inhibidores 5 alfa reductasa"], units: ["mg", "comprimidos"], maxSingleDose: 5 },
  { name: "gliclazida", classes: ["sulfonilureas"], units: ["mg", "comprimidos"], maxSingleDose: 120 },
  { name: "empagliflozina", classes: ["isglt2"], units: ["mg", "comprimidos"], maxSingleDose: 25 },
  { name: "dapagliflozina", classes: ["isglt2"], units: ["mg", "comprimidos"], maxSingleDose: 10 },
  { name: "loratadina", classes: ["antihistaminicos"], units: ["mg", "comprimidos", "ml"], maxSingleDose: 10 },
];
