import { CLINICAL_TEMPLATES } from "@nexus/shared";
import { defineVertical } from "../../manifest";
import { MEDICINE_GOLDEN_CASES } from "./golden";
import { MEDICATION_CATALOG } from "./catalog";

/** Sección SOAP de cada campo de las plantillas clínicas existentes. */
const CANONICAL: Record<string, "S" | "O" | "A" | "P"> = {
  reason: "S",
  present: "S",
  history: "S",
  subjective: "S",
  evolution: "S",
  problems: "S",
  summary: "S",
  question: "S",
  vitals: "O",
  exam: "O",
  objective: "O",
  tests: "O",
  initial: "O",
  reevaluation: "O",
  assessment: "A",
  diagnosis: "A",
  plan: "P",
  treatment: "P",
  instructions: "P",
  interventions: "P",
  followup: "P",
  warnings: "P",
  destination: "P",
  priority: "P",
  observations: "P",
};

/**
 * Vertical médica para consultorio en Argentina.
 *
 * Las plantillas salen de `CLINICAL_TEMPLATES` (@nexus/shared), que es lo
 * que valida la API: el manifiesto nunca puede proponer un campo que el
 * servidor rechace.
 */
export const medicineVertical = defineVertical({
  id: "medicine",
  name: "Nexus Medicina",
  profession: "Médico/a de consultorio",
  version: "1.0.0",
  profile: "healthcare-ar",
  locale: "es-AR",
  timezone: "America/Argentina/Buenos_Aires",
  status: "beta",
  vocabulary: {
    subject: { singular: "paciente", plural: "pacientes" },
    record: { singular: "consulta", plural: "consultas" },
    followup: { singular: "seguimiento", plural: "seguimientos" },
    appointment: { singular: "turno", plural: "turnos" },
    professional: "médico/a",
    domainTerms: [
      "hipertensión", "diabetes", "cefalea", "disnea", "precordalgia", "auscultación", "electrocardiograma",
      "hemograma", "glucemia", "saturación", "ecografía", "radiografía", "amoxicilina", "ibuprofeno",
      "enalapril", "metformina", "levotiroxina", "interconsulta", "evolución", "anamnesis",
    ],
  },
  standard: { name: "HL7 FHIR R4", url: "https://hl7.org/fhir/R4/" },
  entities: [
    {
      id: "patient",
      label: "Paciente",
      standardResource: "Patient",
      sensitive: true,
      identifier: "document",
      storage: "clinical_patients (cifrado AES-256-GCM)",
      fields: [
        { key: "createdAt", label: "Fecha de apertura de la historia", required: true, legalRef: "ley26529.art15.a" },
        { key: "name", label: "Nombre y apellido", required: true, legalRef: "ley26529.art15.b" },
        { key: "document", label: "DNI", legalRef: "ley26529.art15.b" },
        { key: "birthDate", label: "Fecha de nacimiento" },
        { key: "phone", label: "Teléfono" },
        { key: "familyContact", label: "Núcleo familiar / contacto", legalRef: "ley26529.art15.b" },
        { key: "history", label: "Antecedentes genéticos, fisiológicos y patológicos", legalRef: "ley26529.art15.e" },
      ],
    },
    {
      id: "practitioner",
      label: "Profesional",
      standardResource: "Practitioner",
      sensitive: false,
      identifier: "license",
      storage: "users + preferencia clinical_profile, copiado al validar",
      fields: [
        { key: "name", label: "Nombre", required: true, legalRef: "ley26529.art15.c" },
        { key: "specialty", label: "Especialidad", required: true, legalRef: "ley26529.art15.c" },
        { key: "license", label: "Matrícula" },
      ],
    },
    {
      id: "encounter",
      label: "Consulta",
      standardResource: "Encounter",
      sensitive: true,
      storage: "clinical_encounters (borrador → validada, inalterable)",
      fields: [
        { key: "occurredAt", label: "Fecha y hora", required: true, legalRef: "ley26529.art15.d" },
        { key: "fields", label: "Registro de la atención (plantilla)", required: true, legalRef: "ley26529.art15.d" },
        { key: "finalizedAt", label: "Validación del profesional" },
      ],
    },
    {
      id: "condition",
      label: "Problema / diagnóstico",
      standardResource: "Condition",
      sensitive: true,
      storage: "campo assessment de la consulta (texto); codificación estructurada planificada",
      fields: [
        { key: "code", label: "Diagnóstico (CIE-10)", required: true, coding: "CIE-10", legalRef: "ley26529.art15.f" },
        { key: "verificationStatus", label: "Presuntivo / confirmado", required: true },
      ],
    },
    {
      id: "allergy",
      label: "Alergia",
      standardResource: "AllergyIntolerance",
      sensitive: true,
      storage: "patient.allergies",
      fields: [{ key: "substance", label: "Sustancia", required: true }],
    },
    {
      id: "medication",
      label: "Medicación habitual / indicada",
      standardResource: "MedicationStatement",
      sensitive: true,
      storage: "patient.medication y campo plan/treatment",
      fields: [
        { key: "medication", label: "Fármaco", required: true, coding: "ATC" },
        { key: "dosage", label: "Dosis y frecuencia", legalRef: "ley26529.art15.f" },
      ],
    },
    {
      id: "observation",
      label: "Signos vitales y resultados",
      standardResource: "Observation",
      sensitive: true,
      storage: "campo vitals/objective de la consulta",
      fields: [
        { key: "code", label: "Medición", required: true, coding: "LOINC" },
        { key: "value", label: "Valor y unidad", required: true },
      ],
    },
    {
      id: "followup",
      label: "Seguimiento",
      standardResource: "Task",
      sensitive: true,
      storage: "clinical_followups (cifrado)",
      fields: [
        { key: "title", label: "Qué hay que hacer", required: true },
        { key: "dueAt", label: "Vencimiento", required: true },
        { key: "kind", label: "Control / resultado / llamada", required: true },
      ],
    },
    {
      id: "appointment",
      label: "Turno",
      standardResource: "Appointment",
      sensitive: false,
      storage: "events (título solo con iniciales)",
      fields: [
        { key: "startAt", label: "Inicio", required: true },
        { key: "title", label: "Título (iniciales)", required: true },
      ],
    },
    {
      id: "document",
      label: "Estudio / foto / documento",
      standardResource: "DocumentReference",
      sensitive: true,
      storage: "planned (cámara y adjuntos cifrados)",
      fields: [
        { key: "type", label: "Tipo", required: true },
        { key: "attachment", label: "Archivo", required: true },
      ],
    },
    {
      id: "consent",
      label: "Consentimiento",
      standardResource: "Consent",
      sensitive: true,
      storage: "plantilla consent + constancia de dictado en la captura",
      fields: [
        { key: "scope", label: "Alcance (dictado / procedimiento)", required: true },
        { key: "decision", label: "Decisión", required: true },
      ],
    },
    {
      id: "provenance",
      label: "Procedencia",
      standardResource: "Provenance",
      sensitive: false,
      storage: "audit_logs + origen de cada campo propuesto",
      fields: [
        { key: "agent", label: "Quién (profesional / reglas)", required: true },
        { key: "recorded", label: "Cuándo", required: true },
      ],
    },
  ],
  relationships: [
    { from: "encounter", to: "patient", kind: "belongsTo" },
    { from: "encounter", to: "practitioner", kind: "references" },
    { from: "condition", to: "encounter", kind: "belongsTo" },
    { from: "allergy", to: "patient", kind: "belongsTo" },
    { from: "medication", to: "patient", kind: "belongsTo" },
    { from: "observation", to: "encounter", kind: "belongsTo" },
    { from: "followup", to: "patient", kind: "belongsTo" },
    { from: "appointment", to: "patient", kind: "references" },
    { from: "document", to: "patient", kind: "belongsTo" },
    { from: "consent", to: "patient", kind: "belongsTo" },
    { from: "provenance", to: "encounter", kind: "references" },
  ],
  templates: CLINICAL_TEMPLATES.map((t) => ({
    id: t.id,
    name: t.name,
    structure: t.id === "soap" ? "SOAP" : t.id === "consent" ? "Consentimiento informado (Ley 26.529 art. 5)" : "SOAP extendida",
    sections: t.fields.map((f) => ({ key: f.key, label: f.label, canonical: CANONICAL[f.key], aiGenerated: false })),
  })),
  workflows: [
    {
      id: "day-agenda",
      name: "Mi día",
      states: ["planned", "in_progress", "closed"],
      initial: "planned",
      final: ["closed"],
      transitions: [
        { from: "planned", to: "in_progress", trigger: "Abrir Nexus: se arma la agenda con turnos, vencidos y borradores", requiresHuman: false },
        { from: "in_progress", to: "closed", trigger: "Cierre de jornada con borradores validados o reprogramados", requiresHuman: true },
      ],
    },
    {
      id: "encounter",
      name: "Consulta",
      states: ["captured", "draft", "reviewed", "final", "amended"],
      initial: "captured",
      final: ["final", "amended"],
      createsFollowups: true,
      transitions: [
        { from: "captured", to: "draft", trigger: "El profesional confirma el plan propuesto por el dictado", requiresHuman: true },
        { from: "draft", to: "reviewed", trigger: "Revisión de cada campo y vaciado de la transcripción", requiresHuman: true },
        { from: "reviewed", to: "final", trigger: "Validación explícita: la versión queda inalterable", requiresHuman: true },
        { from: "final", to: "amended", trigger: "Corrección como nueva evolución, sin borrar la anterior", requiresHuman: true },
      ],
    },
    {
      id: "followups",
      name: "Seguimientos",
      states: ["pending", "done", "reopened"],
      initial: "pending",
      final: ["done"],
      createsFollowups: true,
      transitions: [
        { from: "pending", to: "done", trigger: "Control, resultado o llamada resuelta", requiresHuman: true },
        { from: "done", to: "reopened", trigger: "Se reabre por novedad", requiresHuman: true },
        { from: "reopened", to: "done", trigger: "Resuelto nuevamente", requiresHuman: true },
      ],
    },
    {
      id: "pending-review",
      name: "Propuestas del asistente",
      states: ["proposed", "confirmed", "discarded"],
      initial: "proposed",
      final: ["confirmed", "discarded"],
      transitions: [
        { from: "proposed", to: "confirmed", trigger: "El profesional marca y confirma el paso", requiresHuman: true },
        { from: "proposed", to: "discarded", trigger: "El profesional lo descarta", requiresHuman: true },
      ],
    },
    {
      id: "intake",
      name: "Alta de paciente",
      states: ["identified", "registered", "archived"],
      initial: "identified",
      final: ["registered", "archived"],
      transitions: [
        { from: "identified", to: "registered", trigger: "Ficha creada con nombre y, si es posible, DNI", requiresHuman: true },
        { from: "registered", to: "archived", trigger: "Archivo de la ficha (se conserva el historial)", requiresHuman: true },
      ],
    },
  ],
  legal: {
    jurisdiction: "AR",
    frameworks: [
      { id: "ley26529", name: "Ley 26.529 — Derechos del paciente, historia clínica y consentimiento informado", url: "https://servicios.infoleg.gob.ar/infolegInternet/anexos/160000-164999/160432/norma.htm" },
      { id: "ley25326", name: "Ley 25.326 — Protección de datos personales (datos sensibles)", url: "https://servicios.infoleg.gob.ar/infolegInternet/anexos/60000-64999/64790/norma.htm" },
      { id: "ley27553", name: "Ley 27.553 — Recetas electrónicas y teleasistencia (Dec. 98/23 y 345/24)", url: "https://servicios.infoleg.gob.ar/infolegInternet/anexos/340000-344999/340919/norma.htm" },
      { id: "ley27706", name: "Ley 27.706 — Programa Federal de historia clínica electrónica", url: "https://servicios.infoleg.gob.ar/infolegInternet/anexos/375000-379999/378946/norma.htm" },
    ],
    recordFields: [
      { ref: "ley26529.art15.a", description: "Fecha de inicio de su confección", coveredBy: ["patient.createdAt"] },
      { ref: "ley26529.art15.b", description: "Datos identificatorios del paciente y su núcleo familiar", coveredBy: ["patient.name", "patient.document", "patient.familyContact"] },
      { ref: "ley26529.art15.c", description: "Datos identificatorios del profesional interviniente y su especialidad", coveredBy: ["practitioner.name", "practitioner.specialty"] },
      { ref: "ley26529.art15.d", description: "Registros claros y precisos de los actos realizados", coveredBy: ["encounter.occurredAt", "encounter.fields"] },
      { ref: "ley26529.art15.e", description: "Antecedentes genéticos, fisiológicos y patológicos", coveredBy: ["patient.history"] },
      { ref: "ley26529.art15.f", description: "Todo acto médico: prescripciones, estudios, diagnóstico presuntivo y de certeza, pronóstico y evolución", coveredBy: ["encounter.fields", "condition.code", "medication.dosage"] },
    ],
    retention: { years: 10, from: "last_activity" },
    appendOnlyAfterSignature: true,
    amendmentsAsNewEntries: true,
    audit: { reads: true, writes: true, actor: true },
    subjectCopySlaHours: 48,
    coding: ["CIE-10", "LOINC", "ATC"],
    authorship: { author: true, specialty: true, timestamp: true, signedAt: true },
    chronological: true,
    sequenced: true,
    regulatedOutputs: [
      {
        id: "prescription",
        description: "Recetas y órdenes de estudios solo se emiten por plataformas inscriptas en ReNaPDiS (Ley 27.553, Dec. 345/24)",
        handledBy: "Nexus registra lo indicado en la consulta; la receta se emite en la plataforma habilitada del profesional",
      },
      {
        id: "digitalSignature",
        description: "La validación de Nexus no es firma digital (Ley 25.506)",
        handledBy: "La versión validada queda inalterable y auditada; la firma digital certificada es una integración pendiente",
      },
    ],
  },
  consent: {
    recording: {
      required: true,
      recordedBy: "human",
      beforeCapture: true,
      statement: "Antes de dictar con el paciente presente, el profesional confirma que informó y obtuvo su consentimiento verbal. Nexus nunca lo afirma por su cuenta.",
    },
    informedConsent: {
      templateId: "consent",
      fields: ["diagnosis", "procedure", "objective", "benefits", "risks", "alternatives", "refusal"],
    },
    revocable: true,
  },
  ai: {
    sensitiveToExternalAI: false,
    sensitiveRouting: "redirect_to_vertical",
    humanReviewRequired: true,
    generatedFields: [
      { field: "encounter.fields", source: "rules", requiresHumanReview: true, initialStatus: "draft" },
      { field: "condition.code", source: "rules", requiresHumanReview: true, initialStatus: "draft" },
      { field: "followup.dueAt", source: "rules", requiresHumanReview: true, initialStatus: "proposed" },
      { field: "appointment.startAt", source: "rules", requiresHumanReview: true, initialStatus: "proposed" },
      { field: "patient.name", source: "rules", requiresHumanReview: true, initialStatus: "proposed" },
      { field: "medication.dosage", source: "rules", requiresHumanReview: true, initialStatus: "draft" },
      { field: "assist.suggestions", source: "ai", requiresHumanReview: true, initialStatus: "proposed" },
    ],
    provisionalCategories: ["diagnosis"],
    provenance: true,
    evidenceLinking: true,
    forbiddenActions: [
      { id: "autonomous_diagnosis", description: "Proponer o confirmar diagnósticos que el profesional no dijo" },
      { id: "dose_generation", description: "Generar o completar dosis: solo se transcriben y se marcan para verificar" },
      { id: "prescription_issuance", description: "Emitir recetas u órdenes (corresponde a plataformas ReNaPDiS)" },
      { id: "consent_fabrication", description: "Registrar consentimiento sin una acción explícita del profesional" },
      { id: "finalize_without_review", description: "Validar una consulta sin revisión y confirmación humana" },
      { id: "external_send_without_confirmation", description: "Enviar datos a terceros sin confirmación" },
      { id: "phi_to_external_ai", description: "Enviar datos identificables de pacientes a proveedores de IA externos" },
    ],
  },
  safety: {
    redFlags: [
      { id: "chest_pain", label: "Dolor torácico", severity: "critical", patterns: ["dolor(?: [a-z]+)?(?: de| en el| en)? (?:toracico|pecho|precordial)", "opresion (?:en el |de )?pecho", "precordalgia", "puntada en el pecho"], escalation: "Descartar síndrome coronario agudo: ECG y evaluación inmediata, derivar a guardia si persiste." },
      { id: "stroke", label: "Signos de ACV", severity: "critical", patterns: ["hemiparesia", "(?:torcio|torcida|desviada|caida) (?:la )?boca", "boca (?:torcida|desviada|caida)", "no (?:puede|podia|pudo) mover (?:el|la) (?:brazo|pierna|mano|lado)", "habla (?:trabado|trabada|arrastrada|arrastrado|rara|raro)", "codigo acv", "perdida de fuerza (?:en |de )?(?:un|el|la) (?:lado|brazo|pierna|hemicuerpo)", "boca torcida", "desviacion de (?:la )?comisura", "dificultad para hablar", "afasia", "disartria"], escalation: "Posible ACV: registrar hora de inicio y derivar de inmediato a un centro con código ACV." },
      { id: "suicide_risk", label: "Riesgo suicida", severity: "critical", patterns: ["ideacion suicida", "ideas? de muerte", "quitarse la vida", "(?:no|sin) (?:tengo |tiene |tenes )?(?:mas )?ganas de vivir", "(?:pienso|piensa|pensando|penso) en (?:tirarme|tirarse|matarme|matarse|morirme|morirse|hacerme dano|hacerse dano)", "tirar(?:me|se) (?:abajo|debajo) (?:del|de un|de una) (?:tren|colectivo|auto|camion)", "(?:quiere|piensa en|pensando en) (?:matarse|morir|suicidarse)", "no quiere (?:seguir )?vivir", "intento de suicidio", "suicid"], escalation: "Evaluar riesgo inminente, no dejar solo al paciente y activar el protocolo de salud mental (Línea 135 / guardia)." },
      { id: "sepsis", label: "Sospecha de sepsis", severity: "critical", patterns: ["sepsis", "shock", "fiebre (?:alta )?con (?:hipotension|confusion|escalofrios intensos)", "hipotension (?:con|y) taquicardia"], escalation: "Sospecha de sepsis: signos vitales completos y derivación urgente." },
      { id: "anaphylaxis", label: "Anafilaxia", severity: "critical", patterns: ["anafilaxia", "edema de (?:glotis|labios|lengua|cara)", "se (?:le |me )?cierra la garganta", "urticaria generalizada", "urticaria generalizada con (?:disnea|falta de aire)"], escalation: "Anafilaxia: adrenalina IM según protocolo y traslado a guardia." },
      { id: "severe_dyspnea", label: "Disnea grave", severity: "high", patterns: ["disnea (?:subita|de reposo|severa|grave)", "no (?:puede|podia|puedo) respirar", "falta de aire (?:subita|en reposo)", "sat(?:uracion)?(?: de oxigeno| de o2| o2)?\\s*(?:de\\s*)?:?\\s*(?:[1-8]\\d|9[0-1])\\s*%"], escalation: "Disnea/hipoxemia: evaluar urgencia y oxigenoterapia." },
      { id: "thunderclap_headache", label: "Cefalea de alarma", severity: "critical", patterns: ["peor (?:dolor de cabeza|cefalea) de su vida", "cefalea (?:subita|en trueno|en estallido)", "cefalea (?:de )?(?:comienzo|inicio) (?:subito|brusco)", "la peor de su vida", "rigidez de nuca"], escalation: "Cefalea de alarma: descartar hemorragia subaracnoidea o meningitis, derivar a guardia." },
      { id: "gi_bleeding", label: "Sangrado digestivo", severity: "high", patterns: ["melena", "hematemesis", "vomitos? con sangre", "sangrado digestivo"], escalation: "Sangrado digestivo: evaluar hemodinamia y derivar." },
      { id: "obstetric", label: "Alarma obstétrica", severity: "critical", patterns: ["embaraz[a-z]*\\b[^.;]{0,80}\\b(?:sangrado|perdidas? de (?:sangre|liquido)|dolor abdominal|contracciones|convulsi|cefalea intensa)", "sangrado (?:vaginal )?(?:en el|durante el) embarazo", "preeclampsia", "eclampsia"], escalation: "Alarma obstétrica: derivación inmediata a guardia obstétrica." },
      { id: "hypertensive_crisis", label: "Crisis hipertensiva", severity: "high", patterns: ["\\b(?:ta|t\\.a\\.|tension arterial|presion(?: arterial)?)(?:\\s+(?:en|de|del|te|le|me|nos|dio|da|consultorio|brazo|derecho|izquierdo))*\\s*(?:de\\s*)?:?\\s*(?:1[89]\\d|2\\d\\d)\\s*(?:/|sobre)\\s*\\d{2,3}", "\\b(?:ta|tension arterial|presion(?: arterial)?)(?:\\s+(?:en|de|del|te|le|me|nos|dio|da|consultorio|brazo|derecho|izquierdo))*\\s*(?:de\\s*)?:?\\s*\\d{2,3}\\s*(?:/|sobre)\\s*(?:1[2-9]\\d)"], escalation: "TA ≥180/120: repetir la medición y buscar daño de órgano blanco." },
      { id: "hypoglycemia", label: "Hipoglucemia", severity: "high", patterns: ["hipoglucemia", "glucemia(?: capilar| en ayunas| central)?\\s*(?:de\\s*)?:?\\s*(?:[1-5]\\d|6[0-9])\\b", "hgt\\s*(?:de\\s*)?:?\\s*(?:[1-5]\\d|6[0-9])\\b"], escalation: "Hipoglucemia: corregir de inmediato y revisar el tratamiento." },
      { id: "violence", label: "Violencia o abuso", severity: "high", patterns: ["violencia (?:de genero|familiar|domestica)", "abuso sexual", "maltrato", "(?:lo|la|le) (?:golpea|golpeo|pega|pego|agrede|agredio)\\b", "(?:pareja|marido|esposo|esposa|novio|novia|ex)\\b[^.;]{0,30}\\b(?:golpe|pego|agredio|amenaz)"], escalation: "Situación de violencia: aplicar el protocolo y ofrecer la Línea 144 / 137." },
    ],
    negationCues: ["niega", "sin", "no presenta", "no refiere", "descarta", "negativo para", "ausencia de", "no tiene", "no hay", "no manifiesta", "no es", "no fue", "no fueron", "afebril"],
    medicationCatalog: MEDICATION_CATALOG,
    allergyCrossCheck: true,
    doseVerification: true,
  },
  capabilities: [
    {
      id: "microphone",
      purpose: "Dictar consultas, pendientes y turnos",
      ios: { infoPlistKeys: ["NSMicrophoneUsageDescription"] },
      android: { permissions: ["android.permission.RECORD_AUDIO"] },
      expoPlugin: { name: "expo-speech-recognition", option: "microphonePermission" },
      rationale: "Nexus usa el micrófono solo mientras tocás Dictar, para transcribir lo que decís sobre tus consultas y pendientes. No escucha en segundo plano ni guarda el audio.",
      fallback: "Escribir con el teclado o usar el dictado del teclado del sistema.",
      status: "implemented",
    },
    {
      id: "speechRecognition",
      purpose: "Convertir el dictado en texto, preferentemente en el dispositivo",
      ios: { infoPlistKeys: ["NSSpeechRecognitionUsageDescription"] },
      android: { permissions: [] },
      expoPlugin: { name: "expo-speech-recognition", option: "speechRecognitionPermission" },
      rationale: "El reconocimiento de voz convierte tu dictado en texto, en el dispositivo cuando está disponible, para preparar borradores que siempre revisás antes de guardar.",
      fallback: "Escribir la nota; el resto de las funciones no cambia.",
      status: "implemented",
    },
    {
      id: "contacts",
      purpose: "Completar el teléfono de un paciente desde la agenda",
      ios: { infoPlistKeys: ["NSContactsUsageDescription"] },
      android: { permissions: ["android.permission.READ_CONTACTS"] },
      expoPlugin: { name: "expo-contacts", option: "contactsPermission" },
      rationale: "Nexus abre tus contactos solo cuando elegís uno, para completar el teléfono de un paciente o de un colega. No sube ni copia tu agenda.",
      fallback: "Escribir el teléfono a mano.",
      prefersSystemPicker: true,
      status: "implemented",
    },
    {
      id: "biometrics",
      purpose: "Bloquear el acceso a las fichas en el teléfono",
      ios: { infoPlistKeys: ["NSFaceIDUsageDescription"] },
      android: { permissions: ["android.permission.USE_BIOMETRIC"] },
      expoPlugin: { name: "expo-local-authentication", option: "faceIDPermission" },
      rationale: "Face ID o la huella protegen el acceso a las fichas de tus pacientes cuando abrís Nexus en este teléfono.",
      fallback: "Se usa el código del dispositivo; sin él, la sección de pacientes queda bloqueada.",
      status: "implemented",
    },
    {
      id: "camera",
      purpose: "Fotografiar estudios, órdenes o documentos del paciente",
      ios: { infoPlistKeys: ["NSCameraUsageDescription"] },
      android: { permissions: ["android.permission.CAMERA"] },
      expoPlugin: { name: "expo-image-picker", option: "cameraPermission" },
      rationale: "La cámara permite fotografiar estudios, órdenes o documentos para adjuntarlos a la ficha de un paciente. Solo se usa cuando lo pedís.",
      fallback: "Adjuntar el archivo desde la computadora o cargar los datos a mano.",
      status: "planned",
    },
    {
      id: "photos",
      purpose: "Elegir una imagen ya tomada",
      ios: { infoPlistKeys: ["NSPhotoLibraryUsageDescription"] },
      android: { permissions: [] },
      expoPlugin: { name: "expo-image-picker", option: "photosPermission" },
      rationale: "El selector de fotos del sistema te deja elegir una imagen puntual de un estudio sin dar acceso a toda tu galería.",
      fallback: "Adjuntar desde la computadora.",
      prefersSystemPicker: true,
      status: "planned",
    },
    {
      id: "calendar",
      purpose: "Ver turnos de Nexus en el calendario del teléfono",
      ios: { infoPlistKeys: ["NSCalendarsFullAccessUsageDescription", "NSCalendarsUsageDescription"] },
      android: { permissions: ["android.permission.READ_CALENDAR", "android.permission.WRITE_CALENDAR"] },
      expoPlugin: { name: "expo-calendar", option: "calendarPermission" },
      rationale: "Con tu permiso, Nexus copia tus turnos al calendario del teléfono usando solo iniciales, nunca datos clínicos.",
      fallback: "Ver la agenda dentro de Nexus o sincronizar con Google Calendar desde Ajustes.",
      status: "planned",
    },
    {
      id: "notifications",
      purpose: "Avisos de seguimientos vencidos y turnos próximos",
      ios: { infoPlistKeys: [] },
      android: { permissions: ["android.permission.POST_NOTIFICATIONS"] },
      expoPlugin: { name: "expo-notifications" },
      rationale: "Las notificaciones te avisan de seguimientos vencidos y del próximo turno, sin nombres ni datos clínicos en el texto del aviso.",
      fallback: "Ver los pendientes en Mi día o recibir el resumen por correo.",
      status: "planned",
    },
  ],
  privacy: {
    sensitiveData: true,
    encryptionAtRest: "AES-256-GCM por registro, con AAD de usuario/tipo/id y búsqueda por HMAC",
    encryptionInTransit: "TLS (HTTPS obligatorio en producción)",
    audioRetention: "not_stored",
    appointmentTitles: "initials",
    noAdvertising: true,
    noTrainingWithoutConsent: true,
    noCloudBackupOfSensitiveData: true,
    accountDeletion: false,
    dataSubjectRights: ["access", "rectification", "portability"],
    localDeviceProtection: "Borradores web cifrados en IndexedDB; en el teléfono no se guardan fichas y el acceso se bloquea con biometría",
  },
  store: {
    category: "Medical",
    disclaimer: "Nexus organiza y registra la práctica del profesional. No diagnostica, no prescribe y no reemplaza el criterio médico: cada dato propuesto se revisa antes de guardarse.",
    privacyPolicyPath: "docs/NEXUS_PRIVACY_POLICY.md",
    appleHealthDataRules: true,
    playHealthDeclaration: true,
    dataSafetyDeclared: true,
  },
  evaluation: {
    referenceNow: "2026-10-05T12:00:00.000Z",
    goldenCases: MEDICINE_GOLDEN_CASES,
    errorTaxonomy: [
      { id: "fabrication", label: "Invención: dato que no se dijo", severity: "major" },
      { id: "omission", label: "Omisión de un dato dicho", severity: "major" },
      { id: "negation", label: "Negación invertida", severity: "major" },
      { id: "attribution", label: "Atribución a otra persona", severity: "major" },
      { id: "medication", label: "Medicación o dosis sin marcar", severity: "major" },
      { id: "timing", label: "Fecha u hora errónea", severity: "minor" },
      { id: "template", label: "Plantilla no óptima", severity: "minor" },
    ],
    releaseThreshold: { maxMajorErrors: 0, minPassRate: 0.9 },
  },
  intents: [
    { id: "capture_encounter", step: "record", permissionLevel: 4, patterns: ["\\b(?:consulta|consulto|viene|vino) (?:por|para)\\b", "\\bpaciente\\b"], example: "Paciente Ana Gómez consulta por tos de 5 días, niega fiebre." },
    { id: "new_patient", step: "subject", permissionLevel: 4, patterns: ["\\bpaciente nuev[oa]\\b", "\\bnuev[oa] paciente\\b", "\\bprimera vez\\b"], example: "Paciente nuevo Juan Pérez, DNI 30.123.456." },
    { id: "followup", step: "followup", permissionLevel: 4, patterns: ["\\bcontrol en\\b", "\\bllamar(?:lo|la)?\\b", "\\bresultados?\\b"], example: "Control en dos semanas con laboratorio." },
    { id: "schedule", step: "appointment", permissionLevel: 2, patterns: ["\\bturno\\b", "\\bagend"], example: "Turno para la paciente Ana Gómez el lunes a las 10." },
  ],
  capture: {
    subjectCues: ["paciente", "pte", "sra", "sr", "senora", "senor", "turno (?:para|con|de)(?: (?:la|el) paciente)?"],
    newSubjectCues: ["\\bpaciente nuev[oa]\\b", "\\bnuev[oa] paciente\\b", "\\bprimera (?:vez|consulta)\\b", "\\bpaciente de primera vez\\b"],
    documentCue: { label: "DNI", pattern: "\\b(?:dni|documento|d\\.n\\.i\\.?)\\s*(?:n(?:ro|umero|°|º)?\\.?\\s*)?:?\\s*(\\d{1,2}\\.?\\d{3}\\.?\\d{3})\\b" },
    defaultTemplate: "progress",
    newSubjectTemplate: "first",
    templateRules: [
      { templateId: "consent", patterns: ["\\bconsentimiento informado\\b"] },
      { templateId: "soap", patterns: ["\\b(?:nota |formato )?soap\\b"] },
      { templateId: "emergency", patterns: ["\\bguardia\\b", "\\burgencia\\b"] },
      { templateId: "referral", patterns: ["\\bderiv(?:o|ar|acion)\\b", "\\binterconsulta\\b"] },
      { templateId: "chronic", patterns: ["\\bcontrol de (?:su |la )?(?:hipertension|hta|diabetes|dbt|epoc|asma|hipotiroidismo|tiroides)\\b", "\\bpaciente cronic[oa]\\b"] },
      { templateId: "progress", patterns: ["\\b(?:viene|vino|vuelve|regresa) (?:a|para) control\\b", "\\bevolucion\\b", "\\bevoluciona\\b"] },
    ],
    sectionCues: [
      { id: "reason", targets: ["reason", "subjective", "problems", "summary", "diagnosis"], patterns: ["\\b(?:consulta|consulto|viene|vino|acude|concurre|ingresa) (?:por|para)\\b", "\\bmotivo(?: de consulta| de derivacion)?:?"] },
      { id: "assessment", targets: ["assessment", "diagnosis"], provisional: true, patterns: ["\\bimpresion diagnostica:?", "\\bdiagnostico presuntivo:?", "\\bimpresiona(?: como)?\\b", "\\bsospecho(?: de)?\\b", "\\bcompatible con\\b", "\\bdx:?", "\\bdiagnostico:?"] },
      { id: "history", targets: ["history", "subjective", "summary", "problems"], patterns: ["\\bantecedentes?(?: personales| familiares)?(?: de)?:?", "\\bap:"] },
      { id: "exam", targets: ["exam", "objective", "initial"], patterns: ["\\bal examen(?: fisico)?:?", "\\bexamen fisico:?", "\\bse constata\\b", "\\bse observa\\b", "\\bausculta(?:cion)?:?"] },
      { id: "tests", targets: ["tests", "objective", "summary"], patterns: ["\\b(?:trae|aporta)\\b", "\\bresultado de\\b"] },
      { id: "plan", targets: ["plan", "treatment", "interventions", "instructions"], patterns: ["\\b(?:le |se )?indic(?:o|a|amos)\\b", "\\bindicaciones:?", "\\bplan:?", "\\btratamiento:?", "\\b(?:receto|recete|roto|suspendo|inicio|inicie|agrego|agregue|continua con|sigue con|arranca con|le doy|le damos|le deje|le subi|le baje|indique|pido|pedi|solicito|solicite)\\b"] },
      { id: "warnings", targets: ["warnings", "instructions", "plan"], patterns: ["\\bpautas de alarma:?", "\\bconsultar si\\b", "\\bvolver si\\b"] },
      { id: "observations", targets: ["observations", "warnings", "followup", "plan"], patterns: ["\\bobservacion(?:es)?:?", "\\bnota:", "\\bcomentario:?", "\\bdejo asentado\\b"] },
      { id: "currentIllness", targets: ["present", "subjective", "evolution", "initial", "summary"], patterns: ["\\benfermedad actual:?"] },
      { id: "destination", targets: ["destination", "plan"], patterns: ["\\bderivo a\\b", "\\bderivar a\\b", "\\binterconsulta con\\b"] },
      { id: "present", targets: ["present", "subjective", "evolution", "initial", "summary"], patterns: ["\\brefiere\\b", "\\bcuenta que\\b", "\\bcomenta\\b", "\\bcursa con\\b", "\\bpresenta\\b"] },
    ],
    measurements: [
      { id: "bp", label: "TA", unit: "mmHg", targets: ["vitals", "objective", "initial", "exam"], pattern: "\\b(?:ta|t\\.a\\.|tension arterial|presion(?: arterial)?)(?:\\s+(?:en|de|del|te|le|me|nos|dio|da|consultorio|brazo|derecho|izquierdo))*\\s*(?:de\\s*)?:?\\s*(\\d{2,3})\\s*(?:/|sobre)\\s*(\\d{2,3})" },
      { id: "hr", label: "FC", unit: "lpm", targets: ["vitals", "objective", "initial", "exam"], pattern: "\\b(?:fc|frecuencia cardiaca|pulso)\\s*(?:de\\s*)?:?\\s*(\\d{2,3})\\b" },
      { id: "rr", label: "FR", unit: "rpm", targets: ["vitals", "objective", "initial", "exam"], pattern: "\\b(?:fr|frecuencia respiratoria)\\s*(?:de\\s*)?:?\\s*(\\d{1,2})\\b" },
      { id: "temp", label: "Temp", unit: "°C", targets: ["vitals", "objective", "initial", "exam"], pattern: "\\b(?:temperatura|temp|fiebre de|t)\\s*(?:de\\s*)?:?\\s*(3\\d(?:[.,]\\d)?)\\s*(?:°\\s*c?|grados)?" },
      { id: "spo2", label: "Sat O2", unit: "%", targets: ["vitals", "objective", "initial", "exam"], pattern: "\\b(?:sat(?:uracion)?(?: de oxigeno| de o2| o2)?|spo2)\\s*(?:de\\s*)?:?\\s*(\\d{2,3})\\s*%?" },
      { id: "weight", label: "Peso", unit: "kg", targets: ["vitals", "objective", "exam"], pattern: "\\bpes[oa]\\s*(?:de\\s*)?:?\\s*(\\d{2,3}(?:[.,]\\d)?)\\s*(?:kg|kilos)?" },
      { id: "glucose", label: "Glucemia", unit: "mg/dL", targets: ["vitals", "tests", "objective"], pattern: "\\b(?:glucemia(?: capilar| en ayunas| central)?|hgt)\\s*(?:de\\s*)?:?\\s*(\\d{2,3})\\b" },
      { id: "age", label: "Edad", unit: "años", targets: ["present", "subjective", "initial", "summary", "reason"], pattern: "\\b(\\d{1,3})\\s+anos\\b" },
    ],
    followupTargets: ["followup"],
    fallbackTargets: ["present", "subjective", "evolution", "initial", "summary", "reason", "instructions", "diagnosis"],
    nameStopWords: [
      "de", "del", "con", "por", "que", "quien", "consulta", "consulto", "viene", "vino", "dni", "documento", "anos", "ano", "y", "e",
      "refiere", "edad", "sexo", "tel", "telefono", "cel", "celular", "control", "para", "a", "en", "la", "el", "se", "le", "lo", "es",
      "esta", "hoy", "manana", "presenta", "tiene", "primera", "nuevo", "nueva", "cuyo", "acude", "concurre", "ingresa", "masculino",
      "femenino", "al", "sin", "niega", "turno", "el", "las", "los",
    ],
    followupRules: [
      { kind: "CALL", title: "Llamar", patterns: ["\\bllamar(?:lo|la|le|los)?\\b", "\\b(?:la|lo|le|los) llamo\\b", "\\bllamada\\b", "\\bcomunicarme\\b", "\\bavisar(?:le)?\\b", "\\bcontactar(?:lo|la)?\\b"] },
      { kind: "RESULT", title: "Revisar resultados", patterns: ["\\bresultados?\\b", "\\b(?:le |les )?(?:pido|pedi|pedimos|pedir|solicito|solicite|solicitamos|solicitar|mando a hacer|que se haga)\\s+(?!que\\b|disculpas\\b|perdon\\b)[a-z]", "\\brevisar (?:el |los |la )?(?:laboratorio|estudios?|analisis)\\b"] },
      { kind: "CONTROL", title: "Control", patterns: ["\\b(?:control|ctrl)\\.?(?: (?!de\\b)[a-z]+){0,3} (?:en|dentro de|el|la|para|a los?|pasado|manana|hoy|este|proximo|\\d+\\s*(?:d|dias|sem|semanas|meses)\\b)", "\\bcontrolar(?:lo|la)?\\b", "\\bvolver a ver(?:lo|la)?\\b", "\\breevaluar\\b", "\\brecontrol", "\\b(?:proximo|nuevo) control\\b", "\\bcontrol (?:mensual|semanal)\\b", "\\b(?:que )?vuelv[ae](?: [a-z]+){0,3} (?:en|el|la|dentro|pasado|manana)\\b", "\\bque (?:me )?(?:la|lo|los) traiga(?:n)?\\b", "\\b(?:la|lo|los) cito\\b", "\\b(?:te|la|lo|los) espero\\b", "\\b(?:la|lo|los|las|nos|te) (?:vemos|veo) (?:en|el|la|dentro|pasado|manana|hoy|la semana)\\b", "\\b(?:la|lo|los|te) (?:volvemos|vuelvo) a ver\\b"] },
    ],
    appointmentCues: ["\\bturno\\b", "\\bagend(?:a|ar|ame|alo|ala)\\b", "\\bcita\\b"],
  },
  suggestions: [
    { id: "overdue-followups", description: "Seguimientos vencidos, empezando por el más atrasado" },
    { id: "results-to-review", description: "Resultados de estudios pendientes de revisar" },
    { id: "calls-today", description: "Llamadas a pacientes para hoy" },
    { id: "stale-drafts", description: "Borradores sin validar (historia completa y firmada)" },
    { id: "free-slot", description: "Huecos de agenda para resolver pendientes" },
    { id: "overload", description: "Agenda sobrecargada" },
    { id: "empty-day", description: "Día sin turnos" },
    { id: "next-appointment", description: "Próximo turno" },
  ],
  routes: {
    home: "/patients/day",
    subjects: "/patients",
    subject: "/patients/:id",
    followups: "/patients/followups",
    capture: "/patients/capture",
    calendar: "/calendar",
  },
});
