import { Router } from "express";
import { aiProvider, isAiConfigured } from "../lib/ai.js";
import { prisma } from "../lib/prisma.js";
import { asyncHandler } from "../middleware/asyncHandler.js";
import { authenticate } from "../middleware/authenticate.js";

export const todayRouter = Router();
todayRouter.use(authenticate);

function ruleBasedInsight(overdueTasks: number, openTaskCount: number, eventsToday: number): string | null {
  if (overdueTasks > 3) {
    return "Tenés varias tareas atrasadas. Podría ser buen momento para reprogramar o archivar las que ya no aplican.";
  }
  if (openTaskCount === 0 && eventsToday === 0) {
    return "No tenés nada pendiente registrado para hoy. Buen momento para planificar la semana.";
  }
  return null;
}

/**
 * Single aggregation endpoint backing the Today screen (spec §10):
 * NOW, PRIORIDADES (max 3), TIMELINE, ATTENTION, and one INSIGHT.
 * The insight is generated by NexusAIProvider when AI_API_KEY is
 * configured (packages/shared-level abstraction, Anthropic today — see
 * lib/ai.ts); it degrades to the original rule-based message with zero
 * behavior change when it isn't, so Phase 1 never depended on a key
 * being present.
 */
todayRouter.get(
  "/",
  asyncHandler(async (req, res) => {
    const userId = req.userId!;
    const now = new Date();
    const startOfDay = new Date(now);
    startOfDay.setHours(0, 0, 0, 0);
    const endOfDay = new Date(now);
    endOfDay.setHours(23, 59, 59, 999);
    const in48h = new Date(now.getTime() + 48 * 60 * 60 * 1000);

    const [user, nextEvent, todaysEvents, openTasks, overdueTasks, upcomingDeadlines] = await Promise.all([
      prisma.user.findUniqueOrThrow({ where: { id: userId }, select: { name: true } }),
      prisma.event.findFirst({
        where: { userId, startAt: { gte: now } },
        orderBy: { startAt: "asc" },
      }),
      prisma.event.findMany({
        where: { userId, startAt: { gte: startOfDay, lte: endOfDay } },
        orderBy: { startAt: "asc" },
      }),
      prisma.task.findMany({
        where: { userId, status: { in: ["TODO", "IN_PROGRESS"] } },
        orderBy: [{ priority: "desc" }, { deadline: "asc" }],
        take: 3,
      }),
      prisma.task.count({
        where: { userId, status: { in: ["TODO", "IN_PROGRESS"] }, deadline: { lt: startOfDay } },
      }),
      prisma.task.findMany({
        where: {
          userId,
          status: { in: ["TODO", "IN_PROGRESS"] },
          deadline: { gte: now, lte: in48h },
        },
        orderBy: { deadline: "asc" },
        take: 5,
      }),
    ]);

    const attention: string[] = [];
    if (overdueTasks > 0) {
      attention.push(`${overdueTasks} tarea${overdueTasks === 1 ? "" : "s"} atrasada${overdueTasks === 1 ? "" : "s"}`);
    }
    for (const task of upcomingDeadlines) {
      attention.push(`"${task.title}" vence pronto`);
    }

    const fallbackInsight = ruleBasedInsight(overdueTasks, openTasks.length, todaysEvents.length);
    let insight = fallbackInsight;

    if (isAiConfigured && (overdueTasks > 0 || openTasks.length > 0 || upcomingDeadlines.length > 0)) {
      const generated = await aiProvider.generateDailyInsight({
        userName: user.name,
        overdueTaskCount: overdueTasks,
        openTaskTitles: openTasks.map((t) => t.title),
        upcomingDeadlines: upcomingDeadlines.map((t) => ({
          title: t.title,
          dueInHours: t.deadline ? Math.max(1, Math.round((t.deadline.getTime() - now.getTime()) / 3_600_000)) : 0,
        })),
        eventsToday: todaysEvents.length,
      });
      if (generated) insight = generated;
    }

    res.json({
      now: nextEvent,
      priorities: openTasks,
      timeline: todaysEvents,
      attention,
      insight,
    });
  })
);
